version: "3.9"

services:
  app:
    volumes:
      - ../app:/app
      - ./php/shared_files/mount/usr/local/etc/php/conf.d/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    container_name: o0h-cakephp4-tutorial-app
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    env_file:
      - ../app.env
    depends_on:
      - database

  webserver:
    image: nginx:alpine
    container_name: o0h-cakephp4-tutorial-webserver
    ports:
      - 8080:80
    volumes:
      - ../app/webroot:/usr/share/nginx/html
      - ./nginx//shared_files/mount/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  database:
    image: mysql:8
    container_name: o0h-cakephp4-tutorial-db
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: my_app
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - 3307:3306
    volumes:
      - ../docker/mysql/mount/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ../docker/mysql/mount/var/lib/mysql:/var/lib/mysql
